# -*- coding: utf-8 -*-
"""AddOn-Sklearn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEp1_PFxgUAfwv4-gSeRX32A6gxtKUeU
"""

import sklearn as sk
from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.tree import *
from sklearn.datasets import *
from sklearn.linear_model import *
from sklearn.metrics import *
from sklearn.svm import *
from sklearn.decomposition import *
from sklearn.ensemble import *
from sklearn.pipeline import *
from sklearn import *
print('Bot | Setting Set AddOn-Sklearn : Sklearn(sk), Sklearn-AddOn(preprocessing, model_selection, tree, datasets, linear_model, metrics, svm, decomposition, ensemble, pipeline')
